FROM java:8
ADD target/UI-employeeManagementSystem-0.0.1-SNAPSHOT.jar UI-employeeManagementSystem-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","UI-employeeManagementSystem-0.0.1-SNAPSHOT.jar"]

