spring:
  datasource:
    url: jdbc:mysql://dockermysql:3306/ems?createDatabaseIfNotExist=true
    username: root
    password: virtusa@1234
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: profile
security:
  oauth2:
    resource:
      token-info-uri: http://dockeroauth:9191/oauth/check_token
    client:
      client-id: web
      client-secret: webpass
server:
  port: 8282

#spring.datasource.initialization-mode=always